import {
  Role,
  User,
  Progja,
  News,
  Himbauan,
  KeuanganState,
  GeraiOutlet,
  KoperasiBiodata,
  OrgMember,
  SystemSettings,
  RoleAccess,
  ActivityLog,
  VotingItem,
} from './types';

// Helper to format date relative to current year/month
const currentYear = new Date().getFullYear();
const currentMonth = String(new Date().getMonth() + 1).padStart(2, '0');

export const INITIAL_BIODATA: KoperasiBiodata = {
  name: 'Koperasi Karyawan Merah Putih Sejahtera',
  address: 'Jl. Jenderal Sudirman No. 45, Jakarta Pusat, DKI Jakarta 10210',
  lat: -6.21462,
  lng: 106.81845,
  phone: '021-5551234',
  email: 'info@koperasimerahputih.co.id',
  facebook: 'https://facebook.com/koperasimerahputih',
  instagram: 'https://instagram.com/koperasimerahputih',
  twitter: 'https://twitter.com/kop_merahputih',
  youtube: 'https://youtube.com/c/koperasimerahputih',
  profilePhoto: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&q=80&w=400',
};

export const INITIAL_USERS: User[] = [
  {
    nik: '11111',
    name: 'Ir. Budi Santoso, M.M.',
    role: 'ketua',
    isRegistered: false,
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
  },
  {
    nik: '22222',
    name: 'Dra. Hj. Siti Rahma, M.Si.',
    role: 'pengawas',
    isRegistered: false,
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
  },
  {
    nik: '33333',
    name: 'Ahmad Dani, S.E.',
    role: 'bendahara',
    isRegistered: false,
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
  },
  {
    nik: '44444',
    name: 'Diana Lestari, S.Sos.',
    role: 'sekretaris',
    isRegistered: false,
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
  },
  {
    nik: '55555',
    name: 'Eko Prasetyo, S.T.',
    role: 'wakil_ketua_usaha',
    isRegistered: false,
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
  },
  {
    nik: '66666',
    name: 'Fitri Handayani, S.Psi.',
    role: 'wakil_ketua_anggota',
    isRegistered: false,
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
  },
];

export const INITIAL_ORG_MEMBERS: OrgMember[] = [
  {
    id: 'm1',
    name: 'Ir. Budi Santoso, M.M.',
    role: 'ketua',
    nik: '11111',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
    phone: '0812-3456-7890',
  },
  {
    id: 'm2',
    name: 'Dra. Hj. Siti Rahma, M.Si.',
    role: 'pengawas',
    nik: '22222',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    phone: '0812-9876-5432',
  },
  {
    id: 'm3',
    name: 'Ahmad Dani, S.E.',
    role: 'bendahara',
    nik: '33333',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
    phone: '0813-1111-2222',
  },
  {
    id: 'm4',
    name: 'Diana Lestari, S.Sos.',
    role: 'sekretaris',
    nik: '44444',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    phone: '0813-3333-4444',
  },
  {
    id: 'm5',
    name: 'Eko Prasetyo, S.T.',
    role: 'wakil_ketua_usaha',
    nik: '55555',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    phone: '0815-5555-6666',
  },
  {
    id: 'm6',
    name: 'Fitri Handayani, S.Psi.',
    role: 'wakil_ketua_anggota',
    nik: '66666',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    phone: '0815-7777-8888',
  },
];

export const INITIAL_PROGJA: Progja[] = [
  {
    id: 'p1',
    title: 'Audit Keuangan Semester I Koperasi',
    picNik: '22222',
    picName: 'Dra. Hj. Siti Rahma, M.Si.',
    picRole: 'pengawas',
    sector: 'Pengawasan',
    targetDate: `${currentYear}-${currentMonth}-25`,
    budget: 5000000,
    fundingSource: 'Kas Operasional Koperasi',
    indicators: 'Laporan hasil audit keuangan terbit dan ditandatangani pengawas serta ketua.',
    description: 'Melakukan pemeriksaan komprehensif terhadap kas keluar masuk, nota belanja, sirkulasi dana pinjaman, dan laporan neraca keuangan selama 6 bulan terakhir.',
    collaborators: ['bendahara' as Role],
    status: 'DISETUJUI',
    createdAt: `${currentYear}-${currentMonth}-01`,
    updatedAt: `${currentYear}-${currentMonth}-02`,
    subTasks: [
      {
        id: 'sub-p1-1',
        title: 'Verifikasi Buku Kas dan Buku Besar Pembantu',
        assignedToNik: '33333',
        assignedToName: 'Ahmad Dani, S.E.',
        assignedToRole: 'bendahara',
        isDone: true,
        dueDate: `${currentYear}-${currentMonth}-15`
      },
      {
        id: 'sub-p1-2',
        title: 'Pemeriksaan Fisik Kas (Cash Count) Brankas',
        assignedToNik: '22222',
        assignedToName: 'Dra. Hj. Siti Rahma, M.Si.',
        assignedToRole: 'pengawas',
        isDone: false,
        dueDate: `${currentYear}-${currentMonth}-20`
      },
      {
        id: 'sub-p1-3',
        title: 'Penyusunan Lembar Temuan Audit Lapangan',
        assignedToNik: '44444',
        assignedToName: 'Diana Lestari, S.Sos.',
        assignedToRole: 'sekretaris',
        isDone: false,
        dueDate: `${currentYear}-${currentMonth}-24`
      }
    ],
  },
  {
    id: 'p2',
    title: 'Pengembangan Unit Usaha Minimarket Gerai Merah Putih',
    picNik: '55555',
    picName: 'Eko Prasetyo, S.T.',
    picRole: 'wakil_ketua_usaha',
    sector: 'Unit Usaha',
    targetDate: `${currentYear}-${currentMonth}-15`,
    budget: 35000000,
    fundingSource: 'Dana Investasi Pengembangan Koperasi',
    indicators: 'Pembukaan cabang gerai ke-3 di area pabrik timur, pengadaan mesin POS baru.',
    description: 'Pengadaan barang dagangan, renovasi tempat, instalasi rak display baru, penyediaan sistem pembayaran elektronik e-wallet guna meningkatkan transaksi harian.',
    collaborators: ['bendahara' as Role, 'sekretaris' as Role],
    status: 'DIPUBLIKASIKAN',
    notesFromKetua: 'Sangat baik, silakan disinkronkan dengan laporan kas dari bendahara.',
    proofPhoto: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&q=80&w=600',
    proofDescription: 'Gerai baru telah resmi dibuka sejak tanggal 5 bulan ini. Transaksi harian mencapai rata-rata 2.5 juta rupiah dengan sistem kasir digital yang lancar.',
    proofReport: 'laporan_gerai_cabang_3.pdf',
    createdAt: `${currentYear}-${currentMonth}-01`,
    updatedAt: `${currentYear}-${currentMonth}-10`,
  },
  {
    id: 'p3',
    title: 'Pendaftaran dan Verifikasi Anggota Baru Gelombang III',
    picNik: '66666',
    picName: 'Fitri Handayani, S.Psi.',
    picRole: 'wakil_ketua_anggota',
    sector: 'Keanggotaan',
    targetDate: `${currentYear}-${currentMonth}-28`,
    budget: 2500000,
    fundingSource: 'Iuran Pendaftaran Anggota Baru',
    indicators: 'Masuknya minimal 150 anggota baru aktif dengan biodata yang tervalidasi.',
    description: 'Sosialisasi manfaat berkoperasi kepada para karyawan baru, pembuatan formulir pendaftaran digital, verifikasi data NIK dan dokumen kelengkapan.',
    collaborators: ['sekretaris' as Role],
    status: 'DIAJUKAN',
    createdAt: `${currentYear}-${currentMonth}-05`,
    updatedAt: `${currentYear}-${currentMonth}-05`,
  },
  {
    id: 'p4',
    title: 'Pembaruan Software Database Keanggotaan Terintegrasi',
    picNik: '44444',
    picName: 'Diana Lestari, S.Sos.',
    picRole: 'sekretaris',
    sector: 'Administrasi',
    targetDate: `${currentYear}-${currentMonth}-18`,
    budget: 8000000,
    fundingSource: 'Dana Taktis Pengurus',
    indicators: 'Sistem database keanggotaan versi 2.0 berjalan tanpa kendala di server lokal.',
    description: 'Migrasi data anggota lama dari excel ke database terenkripsi, pembuatan fitur rekapitulasi keanggotaan otomatis untuk kebutuhan RAT tahunan.',
    collaborators: ['wakil_ketua_anggota' as Role],
    status: 'REVISI',
    notesFromKetua: 'Anggaran terlalu besar untuk modifikasi database lokal. Tolong negosiasikan ulang dengan vendor agar bisa diturunkan menjadi 5 juta rupiah.',
    createdAt: `${currentYear}-${currentMonth}-03`,
    updatedAt: `${currentYear}-${currentMonth}-06`,
  },
  {
    id: 'p5',
    title: 'Penyaluran Pinjaman Lunak Modal Usaha Mikro Anggota',
    picNik: '33333',
    picName: 'Ahmad Dani, S.E.',
    picRole: 'bendahara',
    sector: 'Keuangan',
    targetDate: `${currentYear}-${currentMonth}-12`,
    budget: 50000000,
    fundingSource: 'Sisa Hasil Usaha & Simpanan Wajib',
    indicators: 'Terdistribusinya pinjaman modal usaha kepada 25 anggota pelaku UMKM terverifikasi.',
    description: 'Pencairan dana bantuan pinjaman bunga rendah (0.5% flat) bagi anggota yang memiliki usaha sampingan mikro guna membantu ketahanan ekonomi keluarga.',
    collaborators: ['wakil_ketua_usaha' as Role],
    status: 'DILAKSANAKAN',
    proofPhoto: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=600',
    proofDescription: 'Dana sejumlah 50 juta rupiah telah disalurkan penuh kepada 25 anggota terverifikasi pada tanggal 8 bulan ini. Kwitansi penyaluran dan tanda tangan penerima terlampir.',
    proofReport: 'rekap_penyaluran_pinjaman_umkm.pdf',
    createdAt: `${currentYear}-${currentMonth}-02`,
    updatedAt: `${currentYear}-${currentMonth}-09`,
  },
  {
    id: 'p6',
    title: 'Penyusunan Laporan Pertanggungjawaban Tahunan',
    picNik: '44444',
    picName: 'Diana Lestari, S.Sos.',
    picRole: 'sekretaris',
    sector: 'Administrasi',
    targetDate: `${currentYear}-${currentMonth}-30`,
    budget: 4000000,
    fundingSource: 'Kas Operasional Koperasi',
    indicators: 'Draf LPJ selesai 100% dan siap dicetak untuk dibagikan kepada seluruh pengurus.',
    description: 'Pengumpulan laporan kegiatan dari masing-masing bidang pengurus, penggabungan berkas, desain sampul, dan penggandaan buku laporan pertanggungjawaban.',
    collaborators: ['ketua' as Role, 'bendahara' as Role],
    status: 'DRAFT',
    createdAt: `${currentYear}-${currentMonth}-08`,
    updatedAt: `${currentYear}-${currentMonth}-08`,
  },
];

export const INITIAL_NEWS: News[] = [
  {
    id: 'n1',
    title: 'Rapat Anggota Tahunan (RAT) Sukses Digelar, SHU Alami Kenaikan 15%',
    content: 'RAT tahunan Koperasi Karyawan Merah Putih Sejahtera sukses dilaksanakan di Aula Utama dengan dihadiri oleh 85% anggota aktif. Dalam laporan pertanggungjawaban, Ketua mengumumkan kenaikan sisa hasil usaha (SHU) koperasi sebesar 15% dibandingkan tahun lalu, yang berimbas langsung pada kenaikan dividen yang diterima anggota.',
    photo: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=600',
    date: `${currentYear}-${currentMonth}-02`,
    shares: 42,
    likes: 128,
  },
  {
    id: 'n2',
    title: 'Peluncuran Gerai Ke-3 Guna Mempermudah Kebutuhan Pokok Karyawan',
    content: 'Unit usaha koperasi kembali melangkah maju dengan meresmikan pembukaan Gerai Merah Putih Cabang ke-3 di Pabrik Area Timur. Gerai ini menyajikan berbagai sembako, minuman, makanan ringan, dan kebutuhan kantor dengan harga bersaing. Inisiatif dari Wakil Ketua Bidang Usaha ini disambut sangat antusias oleh karyawan pabrik.',
    photo: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&q=80&w=600',
    date: `${currentYear}-${currentMonth}-06`,
    shares: 18,
    likes: 76,
  },
  {
    id: 'n3',
    title: 'Program Bantuan Sosial Sembako Murah Tanggap Covid & Inflasi',
    content: 'Sebagai bentuk kepedulian sosial koperasi terhadap anggotanya, pengurus berkolaborasi meluncurkan paket sembako bersubsidi senilai Rp 150.000 yang dapat ditebus hanya dengan Rp 50.000 saja. Sebanyak 500 paket ludes terdistribusikan dalam waktu 3 jam pelaksanaan di lapangan parkir koperasi.',
    photo: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&q=80&w=600',
    date: `${currentYear}-${currentMonth}-09`,
    shares: 31,
    likes: 94,
  },
];

export const INITIAL_HIMBAUAN: Himbauan[] = [
  {
    id: 'h1',
    content: 'PENTING: Harap seluruh pengurus segera menyelesaikan penginputan draf Program Kerja sebelum pertengahan bulan ini untuk ditinjau bersama oleh Ketua.',
    senderName: 'Dra. Hj. Siti Rahma, M.Si.',
    senderRole: 'pengawas',
    date: `${currentYear}-${currentMonth}-05`,
    endDate: `${currentYear}-${currentMonth}-20`,
  },
  {
    id: 'h2',
    content: 'Himbauan Penghematan Anggaran: Mengingat kenaikan harga logistik, diimbau agar setiap progja mengoptimalkan dana taktis dan menghindari pengeluaran yang tidak mendesak.',
    senderName: 'Dra. Hj. Siti Rahma, M.Si.',
    senderRole: 'pengawas',
    date: `${currentYear}-${currentMonth}-08`,
    endDate: `${currentYear}-${currentMonth}-25`,
  },
];

export const INITIAL_KEUANGAN: KeuanganState = {
  totalCash: 450000000,
  totalSHU: 125000000,
  budgetPlanned: 107500000,
  budgetUsed: 50000000,
  transactions: [
    {
      id: 't1',
      type: 'IN',
      category: 'Simpanan Wajib',
      amount: 45000000,
      description: 'Penyetoran simpanan wajib bulanan anggota kolektif pabrik A',
      date: `${currentYear}-${currentMonth}-02`,
      requester: 'Diana Lestari, S.Sos. (Sekretaris)',
    },
    {
      id: 't2',
      type: 'OUT',
      category: 'Penyaluran Kredit',
      amount: 50000000,
      description: 'Pencairan modal usaha mikro UMKM bagi 25 anggota terverifikasi',
      date: `${currentYear}-${currentMonth}-09`,
      requester: 'Ahmad Dani, S.E. (Bendahara)',
    },
    {
      id: 't3',
      type: 'IN',
      category: 'Hasil Usaha Gerai',
      amount: 12500000,
      description: 'Penyetoran keuntungan bersih harian toko retail cabang 1 dan 2',
      date: `${currentYear}-${currentMonth}-08`,
      requester: 'Eko Prasetyo, S.T. (Wakil Ketua Usaha)',
    },
    {
      id: 't4',
      type: 'OUT',
      category: 'Pembelian Inventaris',
      amount: 3500000,
      description: 'Pembelian printer barcode thermal dan komputer kasir gerai 3',
      date: `${currentYear}-${currentMonth}-04`,
      requester: 'Eko Prasetyo, S.T. (Wakil Ketua Usaha)',
    },
  ],
  pendingTransactions: [
    {
      id: 'pt-1',
      type: 'OUT',
      category: 'Peralatan Kantor',
      amount: 4500000,
      description: 'Pembelian AC Inverter baru untuk Ruang Administrasi Sekretariat Koperasi',
      date: `${currentYear}-${currentMonth}-10`,
      requesterNik: '44444',
      requesterName: 'Diana Lestari, S.Sos.',
      requesterRole: 'sekretaris',
      status: 'MENUNGGU_PERSETUJUAN',
      changeType: 'BARU'
    },
    {
      id: 'pt-2',
      type: 'IN',
      category: 'Hasil Usaha Gerai',
      amount: 15000000,
      description: 'Koreksi penambahan keuntungan simpanan hasil retail dari Gerai Pusat',
      date: `${currentYear}-${currentMonth}-11`,
      requesterNik: '33333',
      requesterName: 'Ahmad Dani, S.E.',
      requesterRole: 'bendahara',
      status: 'MENUNGGU_PERSETUJUAN',
      changeType: 'BARU'
    }
  ],
};

export const INITIAL_GERAI: GeraiOutlet[] = [
  {
    id: 'g1',
    name: 'Gerai Minimarket Pusat (Pabrik Barat)',
    location: 'Ruko Utama Sektor Barat KM 12',
    sales: 145000000,
    profit: 35000000,
    stock: 2450,
  },
  {
    id: 'g2',
    name: 'Gerai Retail Cabang 2 (Gudang Logistik)',
    location: 'Samping Pos Keamanan Logistik Selatan',
    sales: 85000000,
    profit: 18000000,
    stock: 1200,
  },
  {
    id: 'g3',
    name: 'Gerai Food & Drink Cabang 3 (Kantin Karyawan)',
    location: 'Pabrik Area Timur - Sektor Produksi 4',
    sales: 32000000,
    profit: 7500000,
    stock: 850,
  },
];

export const DEFAULT_ROLE_ACCESS: Record<Role, RoleAccess> = {
  admin_master: {
    dashboard_pengurus: true,
    sirkulasi_prokja: true,
    keuangan: true,
    anggota: true,
    file_download: true,
    biodata_koperasi: true,
    himbauan: true,
    pengaturan_theme: true,
    administrasi_koperasi: true,
    gerai: true,
    akses: true,
  },
  pengawas: {
    dashboard_pengurus: true,
    sirkulasi_prokja: true,
    keuangan: true,
    anggota: true,
    file_download: true,
    biodata_koperasi: false,
    himbauan: true,
    pengaturan_theme: true,
    administrasi_koperasi: false,
    gerai: false,
    akses: false,
  },
  ketua: {
    dashboard_pengurus: true,
    sirkulasi_prokja: true,
    keuangan: false,
    anggota: false,
    file_download: true,
    biodata_koperasi: true,
    himbauan: true,
    pengaturan_theme: true,
    administrasi_koperasi: false,
    gerai: false,
    akses: false,
  },
  bendahara: {
    dashboard_pengurus: true,
    sirkulasi_prokja: true,
    keuangan: true,
    anggota: false,
    file_download: true,
    biodata_koperasi: false,
    himbauan: false,
    pengaturan_theme: true,
    administrasi_koperasi: false,
    gerai: false,
    akses: false,
  },
  wakil_ketua_anggota: {
    dashboard_pengurus: true,
    sirkulasi_prokja: true,
    keuangan: false,
    anggota: true,
    file_download: true,
    biodata_koperasi: false,
    himbauan: false,
    pengaturan_theme: true,
    administrasi_koperasi: false,
    gerai: false,
    akses: false,
  },
  wakil_ketua_usaha: {
    dashboard_pengurus: true,
    sirkulasi_prokja: true,
    keuangan: true,
    anggota: false,
    file_download: true,
    biodata_koperasi: true,
    himbauan: false,
    pengaturan_theme: true,
    administrasi_koperasi: false,
    gerai: true,
    akses: false,
  },
  sekretaris: {
    dashboard_pengurus: true,
    sirkulasi_prokja: true,
    keuangan: false,
    anggota: false,
    file_download: true,
    biodata_koperasi: false,
    himbauan: true,
    pengaturan_theme: true,
    administrasi_koperasi: false,
    gerai: true,
    akses: false,
  },
};

export const INITIAL_SYSTEM_SETTINGS: SystemSettings = {
  alertDaysBefore: 5,
};

export const INITIAL_FILES = [
  { name: 'AD_ART_Koperasi_MP.pdf', size: '2.4 MB', category: 'Legal', date: '2026-01-15' },
  { name: 'Laporan_Keuangan_Tahunan_2025.pdf', size: '4.8 MB', category: 'Keuangan', date: '2026-02-10' },
  { name: 'Formulir_Pengajuan_Pinjaman_v1.docx', size: '320 KB', category: 'Formulir', date: '2026-03-01' },
  { name: 'Standard_Operating_Procedure_Gerai.pdf', size: '1.2 MB', category: 'SOP', date: '2026-04-12' },
  { name: 'Surat_Keputusan_Pengurus_2026.pdf', size: '890 KB', category: 'Legal', date: '2026-05-20' },
];

export const INITIAL_ADMINISTRASI = [
  { id: 'surat-1', type: 'Surat Keputusan', number: '012/SK/KMP/V/2026', subject: 'Pengangkatan Manajer Unit Usaha Gerai 3', date: '2026-05-15', sender: 'Diana Lestari, S.Sos.' },
  { id: 'surat-2', type: 'Surat Keluar', number: '085/OUT/KMP/VI/2026', subject: 'Undangan Rapat Evaluasi Triwulan II', date: '2026-06-10', sender: 'Diana Lestari, S.Sos.' },
  { id: 'surat-3', type: 'Surat Masuk', number: 'SKP-321/IN/VI/2026', subject: 'Pemberitahuan Audit Pajak Tahunan', date: '2026-06-25', sender: 'Kantor Pajak Pratama' },
  { id: 'surat-4', type: 'Surat Tugas', number: '043/ST/KMP/VII/2026', subject: 'Surat Tugas Verifikasi Lapangan Calon Anggota', date: '2026-07-02', sender: 'Budi Santoso, M.M.' },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-07-09 10:14:22',
    userNik: '33333',
    userName: 'Ahmad Dani, S.E.',
    userRole: 'bendahara',
    category: 'keuangan',
    action: 'Tambah Transaksi',
    description: 'Mencatat pengeluaran kas sebesar Rp 1.500.000 untuk Pembelian Kertas & Alat Tulis Kantor.',
  },
  {
    id: 'log-2',
    timestamp: '2026-07-09 11:45:00',
    userNik: '11111',
    userName: 'Ir. Budi Santoso, M.M.',
    userRole: 'ketua',
    category: 'progja',
    action: 'Persetujuan Progja',
    description: 'Menyetujui proposal program kerja "Audit Keuangan Semester I Koperasi" (ID: p1) dengan anggaran Rp 5.000.000.',
  },
  {
    id: 'log-3',
    timestamp: '2026-07-10 08:30:15',
    userNik: '55555',
    userName: 'Eko Prasetyo, S.T.',
    userRole: 'wakil_ketua_usaha',
    category: 'progja',
    action: 'Pengajuan Progja',
    description: 'Mengajukan proposal baru "Pengadaan Genset Cadangan Minimarket" senilai Rp 12.500.000.',
  },
  {
    id: 'log-4',
    timestamp: '2026-07-10 09:15:00',
    userNik: 'admin_master_001',
    userName: 'Ardi (Admin Master)',
    userRole: 'admin_master',
    category: 'system',
    action: 'Perubahan Akses',
    description: 'Memperbarui parameter sirkulasi program kerja dan hak akses menu "Akses Pengurus" di sistem.',
  },
];

export const INITIAL_VOTING: VotingItem[] = [
  {
    id: 'v1',
    title: 'Audit Keuangan Semester I Koperasi (Progja p1)',
    type: 'PROGJA',
    description: 'Voting penentuan kelayakan dan persetujuan pelaksanaan teknis Audit Keuangan Semester I dengan pagu anggaran Rp 5.000.000.',
    targetId: 'p1',
    votes: {
      '11111': 'SETUJU', // Ketua
      '22222': 'SETUJU', // Pengawas
      '33333': 'SETUJU', // Bendahara
    },
    createdAt: `${currentYear}-${currentMonth}-02`,
    endDate: `${currentYear}-${currentMonth}-25`,
    createdByNik: '22222',
    createdByName: 'Dra. Hj. Siti Rahma, M.Si.',
    createdByRole: 'pengawas',
  },
  {
    id: 'v2',
    title: 'Penentuan Lokasi Rapat Koordinasi Anggota Triwulan II',
    type: 'AGENDA',
    description: 'Voting penentuan agenda lokasi dan mekanisme pelaksanaan Rapat Koordinasi Triwulan II: opsi A (Offline di Aula Utama) vs opsi B (Hybrid via Google Meet).',
    votes: {
      '11111': 'SETUJU', // Ketua
      '44444': 'SETUJU', // Sekretaris
      '33333': 'SETUJU', // Bendahara
      '55555': 'TOLAK',   // Wakil Ketua Usaha
      '66666': 'ABSTAIN', // Wakil Ketua Anggota
    },
    createdAt: `${currentYear}-${currentMonth}-04`,
    endDate: `${currentYear}-${currentMonth}-28`,
    createdByNik: '44444',
    createdByName: 'Diana Lestari, S.Sos.',
    createdByRole: 'sekretaris',
  },
  {
    id: 'v3',
    title: 'Pengembangan Unit Usaha Minimarket Gerai Merah Putih (Progja p2)',
    type: 'PROGJA',
    description: 'Voting persetujuan kelayakan pembukaan cabang ke-3 Gerai Merah Putih di Sektor Pabrik Timur dengan investasi Rp 35.000.000.',
    targetId: 'p2',
    votes: {
      '55555': 'SETUJU', // Wakil Ketua Usaha
      '33333': 'SETUJU', // Bendahara
    },
    createdAt: `${currentYear}-${currentMonth}-05`,
    endDate: `${currentYear}-${currentMonth}-20`,
    createdByNik: '55555',
    createdByName: 'Eko Prasetyo, S.T.',
    createdByRole: 'wakil_ketua_usaha',
  },
];


